version: '2'
services:
  registryservice:
    build: registryservice
    mem_limit: 512M
    ports:
      - "8761:8761"
  customerservice:
    build: customerservice
    mem_limit: 512M
    ports:
      - "8181:8181"
    environment:
      - JAVA_OPTS=
         -DEUREKA_URI=http://registryservice:8761/eureka