version: '2'
services:
  registryservice:
    build: registryservice
    mem_limit: 512M
    ports:
      - "8761:8761"
  customerservice:
    build: customerservice
    mem_limit: 512M
    ports:
      - "8181:8181"
    environment:
      - JAVA_OPTS=
         -DEUREKA_URI=http://registryservice:8761/eureka
  gatewayservice:
    build: gatewayservice
    mem_limit: 512M
    ports:
      - "9000:9000"
    links:
      - customerservice:customerservice
      - registryservice:registryservice
    depends_on:
      - customerservice
      - registryservice
